"""empty message

Revision ID: 9e72ad2ae3c6
Revises: 
Create Date: 2019-02-25 03:37:08.262692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e72ad2ae3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('original',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('image_code', sa.String(length=100), nullable=False),
    sa.Column('seg_num', sa.Integer(), nullable=False),
    sa.Column('part_num', sa.Integer(), nullable=False),
    sa.Column('photo', mysql.LONGBLOB(), nullable=True),
    sa.Column('mark_num', sa.Integer(), nullable=False),
    sa.Column('collection_num', sa.Integer(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('org_id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=400), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('collection',
    sa.Column('col_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['original.org_id'], ),
    sa.PrimaryKeyConstraint('col_id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('edit',
    sa.Column('edit_id', sa.Integer(), nullable=False),
    sa.Column('photo', mysql.LONGBLOB(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('mark_id', sa.Integer(), nullable=True),
    sa.Column('date_edited', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['original.org_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('edit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edit')
    op.drop_table('collection')
    op.drop_table('user')
    op.drop_table('original')
    # ### end Alembic commands ###
